version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: auto-db
    hostname: db
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=postgres
    networks:
      - auto-net
    ports:
      - 26257:26257
    volumes:
      - auto-vol:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/seed.sh:/docker-entrypoint-initdb.d/seed.sh
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  auto-vol:

networks:
  auto-net:
    driver: bridge

secrets:
  db-password:
    file: db/passwd.txt
